package main.java;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '云袭' at '16-10-27 上午11:37' with Gradle 2.7
 *
 * @author 云袭, @date 16-10-27 上午11:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
